

model:
  config:
    nmsThreshold: 0.5
    gpuDeviceId: -1
    soft:
      modelPath: soft
      label: soft_open, soft_close, soft_on, soft_off, soft_open_v2, soft_close_v2
    hard:
      modelPath: hard
      label: hard_open, hard_close, hard_none, hard_close_v2, hard_close_v3, hard_open_v2, hard_open_v3, hard_open_or_close